cc_library(
    name = "chess_lib",
    srcs = glob([
        "*.cpp"
    ]),
    hdrs = glob([
        "*.hpp"
    ]),
    deps = [
        "//third_party/sfml:sfml_linux",
    ],
    visibility = ["//visibility:public"]
)
